.TH DOXYSEARCH "1" "27-12-2022" "doxysearch.cgi 1.9.6" "User Commands"
.SH NAME
doxysearch.cgi \- search engine used for searching in doxygen documentation.
.SH SYNOPSIS
.B doxysearch.cgi
.SH DESCRIPTION
CGI binary that is used by doxygen generated HTML output to search for words. 
The tool uses the search index called \fBdoxysearch.db\fR produced by 
doxyindexer. 
.SH SEE ALSO
doxygen(1), doxyindexer(1), doxywizard(1).
